# coding: utf-8

"""
    SDX LC

    You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: yxin@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Link(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'short_name': 'str',
        'ports': 'list[Port]',
        'total_bandwidth': 'float',
        'available_bandwidth': 'float',
        'latency': 'float',
        'packet_loss': 'float',
        'availability': 'float',
        'private_attributes': 'list[str]',
        'time_stamp': 'datetime',
        'measurement_period': 'LinkMeasurementPeriod'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'short_name': 'short_name',
        'ports': 'ports',
        'total_bandwidth': 'total_bandwidth',
        'available_bandwidth': 'available_bandwidth',
        'latency': 'latency',
        'packet_loss': 'packet_loss',
        'availability': 'availability',
        'private_attributes': 'private_attributes',
        'time_stamp': 'time_stamp',
        'measurement_period': 'measurement_period'
    }

    def __init__(self, id=None, name=None, short_name=None, ports=None, total_bandwidth=None, available_bandwidth=None, latency=None, packet_loss=None, availability=None, private_attributes=None, time_stamp=None, measurement_period=None):  # noqa: E501
        """Link - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._short_name = None
        self._ports = None
        self._total_bandwidth = None
        self._available_bandwidth = None
        self._latency = None
        self._packet_loss = None
        self._availability = None
        self._private_attributes = None
        self._time_stamp = None
        self._measurement_period = None
        self.discriminator = None
        self.id = id
        self.name = name
        if short_name is not None:
            self.short_name = short_name
        self.ports = ports
        if total_bandwidth is not None:
            self.total_bandwidth = total_bandwidth
        if available_bandwidth is not None:
            self.available_bandwidth = available_bandwidth
        if latency is not None:
            self.latency = latency
        if packet_loss is not None:
            self.packet_loss = packet_loss
        if availability is not None:
            self.availability = availability
        if private_attributes is not None:
            self.private_attributes = private_attributes
        if time_stamp is not None:
            self.time_stamp = time_stamp
        if measurement_period is not None:
            self.measurement_period = measurement_period

    @property
    def id(self):
        """Gets the id of this Link.  # noqa: E501


        :return: The id of this Link.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Link.


        :param id: The id of this Link.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Link.  # noqa: E501


        :return: The name of this Link.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Link.


        :param name: The name of this Link.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def short_name(self):
        """Gets the short_name of this Link.  # noqa: E501


        :return: The short_name of this Link.  # noqa: E501
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name):
        """Sets the short_name of this Link.


        :param short_name: The short_name of this Link.  # noqa: E501
        :type: str
        """

        self._short_name = short_name

    @property
    def ports(self):
        """Gets the ports of this Link.  # noqa: E501


        :return: The ports of this Link.  # noqa: E501
        :rtype: list[Port]
        """
        return self._ports

    @ports.setter
    def ports(self, ports):
        """Sets the ports of this Link.


        :param ports: The ports of this Link.  # noqa: E501
        :type: list[Port]
        """
        if ports is None:
            raise ValueError("Invalid value for `ports`, must not be `None`")  # noqa: E501

        self._ports = ports

    @property
    def total_bandwidth(self):
        """Gets the total_bandwidth of this Link.  # noqa: E501


        :return: The total_bandwidth of this Link.  # noqa: E501
        :rtype: float
        """
        return self._total_bandwidth

    @total_bandwidth.setter
    def total_bandwidth(self, total_bandwidth):
        """Sets the total_bandwidth of this Link.


        :param total_bandwidth: The total_bandwidth of this Link.  # noqa: E501
        :type: float
        """

        self._total_bandwidth = total_bandwidth

    @property
    def available_bandwidth(self):
        """Gets the available_bandwidth of this Link.  # noqa: E501


        :return: The available_bandwidth of this Link.  # noqa: E501
        :rtype: float
        """
        return self._available_bandwidth

    @available_bandwidth.setter
    def available_bandwidth(self, available_bandwidth):
        """Sets the available_bandwidth of this Link.


        :param available_bandwidth: The available_bandwidth of this Link.  # noqa: E501
        :type: float
        """

        self._available_bandwidth = available_bandwidth

    @property
    def latency(self):
        """Gets the latency of this Link.  # noqa: E501


        :return: The latency of this Link.  # noqa: E501
        :rtype: float
        """
        return self._latency

    @latency.setter
    def latency(self, latency):
        """Sets the latency of this Link.


        :param latency: The latency of this Link.  # noqa: E501
        :type: float
        """

        self._latency = latency

    @property
    def packet_loss(self):
        """Gets the packet_loss of this Link.  # noqa: E501


        :return: The packet_loss of this Link.  # noqa: E501
        :rtype: float
        """
        return self._packet_loss

    @packet_loss.setter
    def packet_loss(self, packet_loss):
        """Sets the packet_loss of this Link.


        :param packet_loss: The packet_loss of this Link.  # noqa: E501
        :type: float
        """

        self._packet_loss = packet_loss

    @property
    def availability(self):
        """Gets the availability of this Link.  # noqa: E501


        :return: The availability of this Link.  # noqa: E501
        :rtype: float
        """
        return self._availability

    @availability.setter
    def availability(self, availability):
        """Sets the availability of this Link.


        :param availability: The availability of this Link.  # noqa: E501
        :type: float
        """

        self._availability = availability

    @property
    def private_attributes(self):
        """Gets the private_attributes of this Link.  # noqa: E501


        :return: The private_attributes of this Link.  # noqa: E501
        :rtype: list[str]
        """
        return self._private_attributes

    @private_attributes.setter
    def private_attributes(self, private_attributes):
        """Sets the private_attributes of this Link.


        :param private_attributes: The private_attributes of this Link.  # noqa: E501
        :type: list[str]
        """

        self._private_attributes = private_attributes

    @property
    def time_stamp(self):
        """Gets the time_stamp of this Link.  # noqa: E501


        :return: The time_stamp of this Link.  # noqa: E501
        :rtype: datetime
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp):
        """Sets the time_stamp of this Link.


        :param time_stamp: The time_stamp of this Link.  # noqa: E501
        :type: datetime
        """

        self._time_stamp = time_stamp

    @property
    def measurement_period(self):
        """Gets the measurement_period of this Link.  # noqa: E501


        :return: The measurement_period of this Link.  # noqa: E501
        :rtype: LinkMeasurementPeriod
        """
        return self._measurement_period

    @measurement_period.setter
    def measurement_period(self, measurement_period):
        """Sets the measurement_period of this Link.


        :param measurement_period: The measurement_period of this Link.  # noqa: E501
        :type: LinkMeasurementPeriod
        """

        self._measurement_period = measurement_period

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Link, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Link):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
